# Generated by Django 4.2.3 on 2023-08-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sem2_task1', '0002_author_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(),
        ),
    ]
